remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-remote-theme

title: yoko 的学习笔记
description: 记录知识，分享心得。A journey of learning.

# 1. 在这里定义集合
collections:
  cs336:
    output: true

# 2. 你的 toc 部分不需要修改，因为 permalink 仍然有效
toc:
  - title: 首页
    url: /

  - title: 我的第一篇文章
    url: /my-first-post/

  - title: CS336 by Stanford
    subfolder:
      - title: Intro
        url: /CS336/intro/
      - title: Assignment
        url: /CS336/assignment/