
#-----------------------------------------------
# 网站基础信息 (Basic Site Information)
#-----------------------------------------------
title: yoko 的学习笔记
description: 记录知识，分享心得。A journey of learning.

#-----------------------------------------------
# 网站部署配置 (Site Deployment Configuration)
# 这是解决白屏问题的关键！请确保没有拼写错误！
#-----------------------------------------------
baseurl: "/tonyl1angyoko.github.io" # 你的仓库名，前面有斜杠 /
url: "https://tonyl1angyoko-alt.github.io" # 你的 GitHub Pages 主域名

#-----------------------------------------------
# 内容集合配置 (Collections Configuration)
# 告诉 Jekyll 处理 _cs336 文件夹
#-----------------------------------------------
collections:
  cs336:
    output: true

#-----------------------------------------------
# 侧边栏目录 (Table of Contents)
#-----------------------------------------------
toc:
  - title: 首页
    url: /

  - title: 我的第一篇文章
    url: /my-first-post/

  - title: CS336 by Stanford
    subfolder:
      - title: Intro
        url: /CS336/intro/
      - title: Assignment
        url: /CS336/assignment/